#!/bin/sh

if [ $# -ne 1 ]; then
  echo "usage: init <name>"
  exit 1
fi

REPOSITORY_DIR=$HOME"/git/"
NEW_REPOSITORY=$REPOSITORY_DIR$1

if [[ ! $NEW_REPOSITORY =~ \.git$ ]]; then
  NEW_REPOSITORY="$NEW_REPOSITORY"".git"
fi

if [[ -d $NEW_REPOSITORY ]]; then
  echo "$NEW_REPOSITORY is exists"
  exit 1
fi

mkdir $NEW_REPOSITORY
git init --bare --shared $NEW_REPOSITORY

