#!/bin/sh

if [ $# -ne 1 ]; then
  echo "usage: init <name>"
  exit 1
fi

repoDir=$HOME"/git/"
newRepo=$repoDir$1

if [[ ! $newRepo =~ \.git$ ]]; then
  newRepo="$newRepo"".git"
fi

if [[ -d $newRepo ]]; then
  echo "$newRepo is exists"
  exit 1
fi

mkdir $newRepo
git init --bare --shared $newRepo

