#!/bin/sh

if [ $# -ne 1 ];then
  echo "usage: rm <name>"
  exit 1
fi

repoDir=$HOME"/git/"
target=$1
[[ $repoDir$target =~ \.git$ ]] || target=$target".git"
if [[ ! -d $repoDir$target ]];then
  echo "$target is not exists"
  exit 1
fi

backupDir=$HOME"/git.bak/"
today=`date "+-%Y-%m-%d"`
if [[ -d $backupDir$target$today ]];then
  i=1
  while [ -d $backupDir$target$today"-"$i ]
  do
    i=`expr "$i" + 1`
  done
  today=$today"-"$i
fi

mv $repoDir$target $backupDir$target$today

